import { useParams, Link } from "react-router-dom";
import { useReport } from "../hooks/useReports";
import { ReportStatusBadge } from "../components/ReportStatusBadge";
import { ArchiveReportDialog } from "../components/ArchiveReportDialog";
import { SnapshotViewer } from "../components/SnapshotViewer";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Archive, Calendar, User, FileText, Activity } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";

export function ReportDetailPage() {
  const { id } = useParams<{ id: string }>();
  const { data: report, isLoading, isError } = useReport(id!);

  if (isLoading) {
    return (
      <div className="p-8 max-w-5xl mx-auto space-y-6">
        <Skeleton className="h-10 w-48" />
        <Skeleton className="h-32 w-full" />
        <Skeleton className="h-64 w-full" />
      </div>
    );
  }

  if (isError || !report) {
    return (
      <div className="p-8 max-w-5xl mx-auto text-center space-y-4">
        <h2 className="text-2xl font-bold">Report not found</h2>
        <p className="text-muted-foreground">The report you are looking for does not exist or you don't have access.</p>
        <Link to="/reports">
          <Button variant="outline">Back to Reports</Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="p-8 max-w-5xl mx-auto space-y-8">
      <div className="flex items-center justify-between">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-sm text-muted-foreground mb-4">
            <Link to="/reports" className="hover:text-primary transition-colors flex items-center">
              <ArrowLeft className="w-4 h-4 mr-1" />
              Reports
            </Link>
            <span>/</span>
            <span>{report.reportNumber}</span>
          </div>
          <div className="flex items-center gap-3">
            <h1 className="text-3xl font-bold tracking-tight">Report {report.reportNumber}</h1>
            <ReportStatusBadge status={report.reportStatus} />
          </div>
        </div>
        <div className="flex items-center gap-2">
          {report.reportStatus !== "ARCHIVED" && (
            <ArchiveReportDialog reportId={report.id}>
              <Button variant="outline" className="text-destructive hover:text-destructive">
                <Archive className="h-4 w-4 mr-2" />
                Archive Report
              </Button>
            </ArchiveReportDialog>
          )}
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-card border rounded-lg p-4 space-y-1">
          <div className="flex items-center text-sm font-medium text-muted-foreground gap-2">
            <FileText className="w-4 h-4" /> Type
          </div>
          <div className="font-semibold">{report.reportType.replace(/_/g, " ")}</div>
        </div>
        <div className="bg-card border rounded-lg p-4 space-y-1">
          <div className="flex items-center text-sm font-medium text-muted-foreground gap-2">
            <Calendar className="w-4 h-4" /> Generated At
          </div>
          <div className="font-semibold">{new Date(report.generatedAt).toLocaleString()}</div>
        </div>
        <div className="bg-card border rounded-lg p-4 space-y-1">
          <div className="flex items-center text-sm font-medium text-muted-foreground gap-2">
            <User className="w-4 h-4" /> Generated By
          </div>
          <div className="font-semibold">{report.generatedBy}</div>
        </div>
        <div className="bg-card border rounded-lg p-4 space-y-1">
          <div className="flex items-center text-sm font-medium text-muted-foreground gap-2">
            <Activity className="w-4 h-4" /> Source
          </div>
          <div className="font-semibold">{report.reportSource} (v{report.reportVersion})</div>
        </div>
      </div>

      <div className="space-y-4">
        <h3 className="text-xl font-semibold border-b pb-2">Report Snapshot</h3>
        {report.snapshot ? (
          <SnapshotViewer data={report.snapshot.snapshotData} />
        ) : (
          <div className="p-12 text-center border border-dashed rounded-lg bg-muted/20">
            <p className="text-muted-foreground">Snapshot data is unavailable for this report.</p>
          </div>
        )}
      </div>
    </div>
  );
}
