"""p1_multi_company_isolation

Revision ID: 1bfd7ef2246b
Revises: c76f68cb3c38
Create Date: 2026-06-03 22:39:41.561960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfd7ef2246b'
down_revision: Union[str, Sequence[str], None] = 'c76f68cb3c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('company_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'attendances', 'companies', ['company_id'], ['id'])
    op.add_column('companies', sa.Column('registration_number', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('contact_phone', sa.String(), nullable=True))
    
    # Safely rename column instead of dropping and adding
    op.alter_column('companies', 'name', new_column_name='company_name')
    
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_constraint(op.f('uq_company_name'), 'companies', type_='unique')
    op.create_unique_constraint('uq_company_name', 'companies', ['company_name'])
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'address')
    op.create_unique_constraint('uq_company_site_name', 'sites', ['company_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_company_site_name', 'sites', type_='unique')
    op.add_column('companies', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_constraint('uq_company_name', 'companies', type_='unique')
    
    # Revert rename
    op.alter_column('companies', 'company_name', new_column_name='name')
    
    op.create_unique_constraint(op.f('uq_company_name'), 'companies', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.drop_column('companies', 'contact_phone')
    op.drop_column('companies', 'contact_email')
    op.drop_column('companies', 'registration_number')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'company_id')
    # ### end Alembic commands ###
