"""add_soft_delete_mixin

Revision ID: 70b43e86330a
Revises: 88a9120bc0c4
Create Date: 2026-07-03 12:51:53.763026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b43e86330a'
down_revision: Union[str, Sequence[str], None] = '88a9120bc0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('companies', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contractors', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('contractors', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('departments', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('departments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('sites', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('sites', 'deleted_at')
    op.drop_column('sites', 'is_deleted')
    op.drop_column('departments', 'deleted_at')
    op.drop_column('departments', 'is_deleted')
    op.drop_column('contractors', 'deleted_at')
    op.drop_column('contractors', 'is_deleted')
    op.drop_column('companies', 'deleted_at')
    op.drop_column('companies', 'is_deleted')
    # ### end Alembic commands ###
