"""hardening_sprint_db_indexes

Revision ID: bfa04f480ce6
Revises: c54b462e961a
Create Date: 2026-06-01 02:19:35.433582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa04f480ce6'
down_revision: Union[str, Sequence[str], None] = 'c54b462e961a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_attendances_site_id_check_in_time', 'attendances', ['site_id', 'check_in_time'], unique=False)
    op.create_index('ix_attendances_user_id_check_in_time', 'attendances', ['user_id', 'check_in_time'], unique=False)
    op.create_unique_constraint('uq_company_name', 'companies', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_company_name', 'companies', type_='unique')
    op.drop_index('ix_attendances_user_id_check_in_time', table_name='attendances')
    op.drop_index('ix_attendances_site_id_check_in_time', table_name='attendances')
    # ### end Alembic commands ###
