"""Sprint 2 sites attendance occupancy

Revision ID: c54b462e961a
Revises: ccd40482e974
Create Date: 2026-06-01 02:07:12.053200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54b462e961a'
down_revision: Union[str, Sequence[str], None] = 'ccd40482e974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor_to_site',
    sa.Column('contractor_id', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], )
    )
    op.create_table('department_to_site',
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], )
    )
    op.create_table('occupancy_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_workers', sa.Integer(), nullable=True),
    sa.Column('department_breakdown', sa.JSON(), nullable=True),
    sa.Column('contractor_breakdown', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_qr_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('qr_token', sa.String(), nullable=True),
    sa.Column('qr_image', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_qr_codes_qr_token'), 'site_qr_codes', ['qr_token'], unique=True)
    op.create_table('worker_to_site',
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], )
    )
    op.add_column('attendances', sa.Column('gps_latitude', sa.Float(), nullable=True))
    op.add_column('attendances', sa.Column('gps_longitude', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('geofence_radius_meters', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('sites', 'radius')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('radius', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('sites', 'created_at')
    op.drop_column('sites', 'geofence_radius_meters')
    op.drop_column('attendances', 'gps_longitude')
    op.drop_column('attendances', 'gps_latitude')
    op.drop_table('worker_to_site')
    op.drop_index(op.f('ix_site_qr_codes_qr_token'), table_name='site_qr_codes')
    op.drop_table('site_qr_codes')
    op.drop_table('occupancy_snapshots')
    op.drop_table('department_to_site')
    op.drop_table('contractor_to_site')
    # ### end Alembic commands ###
