"""ws7_p5c_attendance_workspace

Revision ID: de362e3a9238
Revises: 31ad79ac9318
Create Date: 2026-07-10 23:18:54.979572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de362e3a9238'
down_revision: Union[str, Sequence[str], None] = '31ad79ac9318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_attendances_company_id', 'attendances', ['company_id'], unique=False)
    op.create_index('ix_attendances_site_id', 'attendances', ['site_id'], unique=False)
    op.create_index('ix_attendances_site_id_check_out_time', 'attendances', ['site_id', 'check_out_time'], unique=False)
    op.create_index('ix_attendances_user_id', 'attendances', ['user_id'], unique=False)
    op.create_index('ix_attendances_user_id_check_out_time', 'attendances', ['user_id', 'check_out_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendances_user_id_check_out_time', table_name='attendances')
    op.drop_index('ix_attendances_user_id', table_name='attendances')
    op.drop_index('ix_attendances_site_id_check_out_time', table_name='attendances')
    op.drop_index('ix_attendances_site_id', table_name='attendances')
    op.drop_index('ix_attendances_company_id', table_name='attendances')
    # ### end Alembic commands ###
