// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoCAbf4YViMEAyC-LreOD3cg7k4FN__lU',
    appId: '1:895950491735:web:dac9acb2c0353856745312',
    messagingSenderId: '895950491735',
    projectId: 'constructpulse',
    authDomain: 'constructpulse.firebaseapp.com',
    storageBucket: 'constructpulse.firebasestorage.app',
    measurementId: 'G-T99TE2F3ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoDj5UU8EUFu-sRzs5o5S7de09oOO9I8A',
    appId: '1:895950491735:android:5305c543932efd28745312',
    messagingSenderId: '895950491735',
    projectId: 'constructpulse',
    storageBucket: 'constructpulse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFjHpZPQ__jBUewudpaZsvJxtRcUZ-PO4',
    appId: '1:895950491735:ios:53fbc1ad31c3967d745312',
    messagingSenderId: '895950491735',
    projectId: 'constructpulse',
    storageBucket: 'constructpulse.firebasestorage.app',
    iosBundleId: 'com.constructpulse.constructpulse',
  );
}
